### ISSUE TITLE
Path planner debugging and finalization

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#15]
Priority: Mid

**Comment by AadityaAgni** [comment]
Path Planner movement issue has been identified(i.e. the error where the robot would launch itself forward rather than turn backwards, as we saw in DCMP)

Reason for the bug: Discrepancy between gyro values received by odometry and pathplanner. Pathplanner would receive a flipped gyro value and move the robot relative to the position it was given, while odometry registered that as the opposite direction since it is given the correct gyro value. In an effort to compensate, the robot would accelerate in what pathplanner thought was the correct direction, but would continue to get negative gyro values.

Fix: Our current fix is that we flip the gyro values for both odometry AND pathplanner by changing the getRotation2D() method, but only flipping in auto so it isn't flipped in teleop. Theoretically, because pathplanner uses field oriented gyro values, if we flip the path to the other side this won't work because the gyro values would again need to be flipped. 

Potential future fixes: PoseEstimation/Vision(Issue #14 ), some way to flip gyro values based off of what DriverStation says is the correct side
