### ISSUE TITLE
Enable JUnit test framework

### ISSUE THREAD

**Issue by geeknoid** [FRC-1294/frc2024#91]
We need to support running JUnit tests from VS code and as a PR gate.

**Comment by tcdoan** [comment]
I think tests should base on a realistic simulation so that any tests can catch any 'harmful' code changes whenever we swap motors, encoders/sensors, or add new lines of code. I took a look at Ankit simulation code and [WPILib Physics Simulation](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-simulation/physics-sim.html) but not satisfied yet. Looking at https://github.com/wpilibsuite/allwpilib/pull/3374 at the moment

**Comment by TejaKoripellaUwU** [comment]
Not on plan for current preseason.
